### ISSUE TITLE
종만북 LIS 최적화 방법에 대해 고민하기.

### ISSUE THREAD

**Issue by ChoiWheatley** [ChoiWheatley/choi-workspace#17]
문제링크 : https://algospot.com/judge/problem/read/LIS
O(N^2) 시간에 문제를 푸는 것은 쉽다. 하지만 O(NlgN) 시간에 문제를 푸는 방식이 위키피디아에 나와있으나 이해할 수 없다. 아직 내가 수준에 미달한 건가?

**Comment by ChoiWheatley** [comment]
https://en.wikipedia.org/wiki/Longest_increasing_subsequence
https://seungkwan.tistory.com/8

**Comment by kdgyun** [comment]
dp로 풀 경우 보통 한 개의 원소(i)에 대하여 이전 원소들을 훑으면서 새 sequance를 만들기 때문에 N^2 time complexity 이지만, 훑는 과정을 binary search를 이용하여 리스트의 끝 값과 비교하여 새 시퀀스에 바꾸거나 채워 놓는 방식으로 변경하면 NlogN에 처리가 가능.

https://st-lab.tistory.com/137 의 가장 하단에 접은 글로 코드가 구현되어있긴 함.
c/c++ 의 경우 lower bound로 구현 가능.

**Comment by kdgyun** [comment]
> dp로 풀 경우 보통 한 개의 원소(i)에 대하여 이전 원소들을 훑으면서 새 sequance를 만들기 때문에 N^2 time complexity 이지만, 훑는 과정을 binary search를 이용하여 리스트의 끝 값과 비교하여 새 시퀀스에 바꾸거나 채워 놓는 방식으로 변경하면 NlogN에 처리가 가능.
> 
> https://st-lab.tistory.com/137 의 가장 하단에 접은 글로 코드가 구현되어있긴 함.
> c/c++ 의 경우 lower bound로 구현 가능.

seq 출력까지 해결 완료~~~~
